---

name:
    bnb-staking-csvs
version:
    0.1.0.0
github:
    prikhi/bnb-staking-csvs
homepage:
    https://github.com/prikhi/bnb-staking-csvs#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2021 Pavan Rikhi
category:
    Web, Finance, Console
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate CSV Exports of Your BNB Staking Rewards.

description: |
    @bnb-staking-csvs@ is a CLI program that queries the Binance.org API for
    all of a delegator's rewards and exports the resulting data to a CSV file.

    You can install @bnb-staking-csvs@ with Stack: @stack install --resolver
    nightly bnb-staking-csvs@. Then run the following to print out your
    rewards in CSV format:

    @
      bnb-staking-rewards \<DELEGATOR_PUBKEY>
    @


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - aeson < 2
        - bytestring < 1
        - cassava < 1
        - req >= 3 && < 4
        - scientific < 1
        - text >= 1 && < 2
        - time >= 1 && < 2

executables:
    bnb-staking-csvs:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - bnb-staking-csvs

tests:
    bnb-staking-csvs-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - bnb-staking-csvs
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
